name: 'GitHub Badges Action'
description: 'Generates a list of badges from a JSON file (using ShieldsIo and SimpleIcons)'
author: 'Guilherme Branco Stracini'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'award'
  color: 'green'

# Define your inputs here.
inputs:
  milliseconds:
    description: 'Your input description here'
    required: true
    default: '1000'

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
